apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-openshift
  name: hello-openshift
  namespace: ocpupskill
spec:
  containers:
  - image: openshift/hello-openshift
    name: hello-openshift
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
