---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-openshift
---
apiVersion: v1
kind: Service
metadata:
  name: hello-openshift
  namespace: hello-openshift
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: hello-openshift
  type: ClusterIP
---
kind: Pod
apiVersion: v1
metadata:
  name: hello-openshift
  namespace: hello-openshift
  labels:
    name: hello-openshift
spec:
  containers:
  - name: hello-openshift
    image: openshift/hello-openshift
    ports:
    - containerPort: 8080
      protocol: TCP
    resources: {}
    volumeMounts:
    - name: tmp
      mountPath: "/tmp"
    terminationMessagePath: "/dev/termination-log"
    imagePullPolicy: IfNotPresent
    securityContext:
      capabilities: {}
      privileged: false
  volumes:
  - name: tmp
    emptyDir: {}
  restartPolicy: Always
  dnsPolicy: ClusterFirst
  serviceAccount: ''
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: hello-openshift
  namespace: hello-openshift
spec:
  rules:
  - host: hello-openshift.lab.int
    http:
     paths:
     - path: /
       pathType: Exact
       backend:
         service:
           name: hello-openshift
           port:
             number: 8080
